mongo:
  uri: "mongodb://127.0.0.1:27017"
  db: "glamira_project"
  raw_collection: "raw_data"
  ip_collection: "ip_locations"
  product_collection: "product_names"

ip2location:
  bin_path: "data/ip2location/IP-COUNTRY-REGION-CITY.BIN"

processing:
  batch_size: 1000
  export_csv: true
  csv_path: "data/ip_locations.csv"

gcp:
  project_id: "todo-459814"
  bucket_name: "glamira-raw-data-bucket"
  bq_dataset: "glamira_raw"
  location: "US"

export:
  source_collection_keys:
    - "raw_collection"
    - "product_collection"
    - "ip_collection"
  batch_size: 50000
  gcs_prefix: "raw"

logging:
  level: "INFO"

bq_load:
  - name: product_names
    source: "raw/product_names/*/*.jsonl"
    table: "product_names_raw"
    mode: "simple"

  - name: ip_locations
    source: "raw/ip_locations/*/*.jsonl"
    table: "ip_locations_raw"
    mode: "simple"

  - name: raw_data
    source: "raw/raw_data/*/*/*.jsonl"
    table: "raw_events"
    mode: "raw"